language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "sudo chmod 700 ./gradlew"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - skatjr30@naver.com